import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { readFileSync } from 'fs';
import {
  parseNetscapeCookieFile,
  filterCookiesForUrl,
  resolveCookieFile,
  loadCookiesFromFile,
  mergeCookies,
} from '../fetch/cookie-file.js';
import type { NetscapeCookie } from '../fetch/cookie-file.js';

vi.mock('fs', async (importOriginal) => {
  const actual = await importOriginal<typeof import('fs')>();
  return { ...actual, readFileSync: vi.fn(actual.readFileSync) };
});

describe('parseNetscapeCookieFile', () => {
  it('parses valid cookie lines', () => {
    const content = `.example.com\tTRUE\t/\tFALSE\t0\tsession_id\tabc123
.example.org\tTRUE\t/api\tTRUE\t1893456000\ttoken\txyz789`;

    const cookies = parseNetscapeCookieFile(content);
    expect(cookies).toHaveLength(2);

    expect(cookies[0]).toEqual({
      domain: '.example.com',
      includeSubdomains: true,
      path: '/',
      secure: false,
      expires: 0,
      name: 'session_id',
      value: 'abc123',
    });

    expect(cookies[1]).toEqual({
      domain: '.example.org',
      includeSubdomains: true,
      path: '/api',
      secure: true,
      expires: 1893456000,
      name: 'token',
      value: 'xyz789',
    });
  });

  it('skips comment lines', () => {
    const content = `# Netscape HTTP Cookie File
# This is a comment
.example.com\tTRUE\t/\tFALSE\t0\tname\tvalue`;

    const cookies = parseNetscapeCookieFile(content);
    expect(cookies).toHaveLength(1);
    expect(cookies[0].name).toBe('name');
  });

  it('skips blank lines', () => {
    const content = `.example.com\tTRUE\t/\tFALSE\t0\tname\tvalue

.example.org\tTRUE\t/\tFALSE\t0\tother\tval`;

    const cookies = parseNetscapeCookieFile(content);
    expect(cookies).toHaveLength(2);
  });

  it('skips malformed lines with too few fields', () => {
    const content = `.example.com\tTRUE\t/\tFALSE
.example.com\tTRUE\t/\tFALSE\t0\tname\tvalue`;

    const cookies = parseNetscapeCookieFile(content);
    expect(cookies).toHaveLength(1);
  });

  it('skips lines with non-numeric expires', () => {
    const content = `.example.com\tTRUE\t/\tFALSE\tnotanumber\tname\tvalue
.example.com\tTRUE\t/\tFALSE\t0\tgood\tvalue`;

    const cookies = parseNetscapeCookieFile(content);
    expect(cookies).toHaveLength(1);
    expect(cookies[0].name).toBe('good');
  });

  it('handles empty content', () => {
    expect(parseNetscapeCookieFile('')).toEqual([]);
  });

  it('handles typical browser export with header', () => {
    const content = `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by an extension. Do not edit.

.example.com\tTRUE\t/\tTRUE\t1893456000\tauth\tsecret123`;

    const cookies = parseNetscapeCookieFile(content);
    expect(cookies).toHaveLength(1);
    expect(cookies[0].name).toBe('auth');
  });
});

describe('filterCookiesForUrl', () => {
  const baseCookie: NetscapeCookie = {
    domain: '.example.com',
    includeSubdomains: true,
    path: '/',
    secure: false,
    expires: 0,
    name: 'test',
    value: 'val',
  };

  function makeCookie(overrides: Partial<NetscapeCookie>): NetscapeCookie {
    return { ...baseCookie, ...overrides };
  }

  describe('domain matching', () => {
    it('matches exact domain', () => {
      const cookies = [makeCookie({ domain: 'example.com', includeSubdomains: false })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/page');
      expect(result).toEqual({ test: 'val' });
    });

    it('matches subdomain with dot prefix', () => {
      const cookies = [makeCookie({ domain: '.example.com' })];
      const result = filterCookiesForUrl(cookies, 'https://sub.example.com/page');
      expect(result).toEqual({ test: 'val' });
    });

    it('matches root domain with dot prefix', () => {
      const cookies = [makeCookie({ domain: '.example.com' })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/page');
      expect(result).toEqual({ test: 'val' });
    });

    it('prevents suffix attacks (badexample.com should not match .example.com)', () => {
      const cookies = [makeCookie({ domain: '.example.com' })];
      const result = filterCookiesForUrl(cookies, 'https://badexample.com/page');
      expect(result).toEqual({});
    });

    it('rejects non-matching domain', () => {
      const cookies = [makeCookie({ domain: '.example.com' })];
      const result = filterCookiesForUrl(cookies, 'https://other.org/page');
      expect(result).toEqual({});
    });

    it('rejects subdomain when includeSubdomains is false', () => {
      const cookies = [makeCookie({ domain: 'example.com', includeSubdomains: false })];
      const result = filterCookiesForUrl(cookies, 'https://sub.example.com/page');
      expect(result).toEqual({});
    });
  });

  describe('path matching', () => {
    it('matches exact path', () => {
      const cookies = [makeCookie({ path: '/api' })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/api');
      expect(result).toEqual({ test: 'val' });
    });

    it('matches path prefix', () => {
      const cookies = [makeCookie({ path: '/api' })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/api/v1/data');
      expect(result).toEqual({ test: 'val' });
    });

    it('rejects path with same prefix but no segment boundary (/api vs /apiv2)', () => {
      const cookies = [makeCookie({ path: '/api' })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/apiv2');
      expect(result).toEqual({});
    });

    it('rejects non-matching path', () => {
      const cookies = [makeCookie({ path: '/api' })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/web');
      expect(result).toEqual({});
    });

    it('root path matches everything', () => {
      const cookies = [makeCookie({ path: '/' })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/any/path');
      expect(result).toEqual({ test: 'val' });
    });
  });

  describe('secure flag', () => {
    it('allows secure cookies on HTTPS', () => {
      const cookies = [makeCookie({ secure: true })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/');
      expect(result).toEqual({ test: 'val' });
    });

    it('rejects secure cookies on HTTP', () => {
      const cookies = [makeCookie({ secure: true })];
      const result = filterCookiesForUrl(cookies, 'http://example.com/');
      expect(result).toEqual({});
    });

    it('allows non-secure cookies on HTTP', () => {
      const cookies = [makeCookie({ secure: false })];
      const result = filterCookiesForUrl(cookies, 'http://example.com/');
      expect(result).toEqual({ test: 'val' });
    });
  });

  describe('expiry', () => {
    it('allows session cookies (expires=0)', () => {
      const cookies = [makeCookie({ expires: 0 })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/');
      expect(result).toEqual({ test: 'val' });
    });

    it('allows cookies with future expiry', () => {
      const futureTs = Math.floor(Date.now() / 1000) + 86400;
      const cookies = [makeCookie({ expires: futureTs })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/');
      expect(result).toEqual({ test: 'val' });
    });

    it('rejects expired cookies', () => {
      const pastTs = Math.floor(Date.now() / 1000) - 86400;
      const cookies = [makeCookie({ expires: pastTs })];
      const result = filterCookiesForUrl(cookies, 'https://example.com/');
      expect(result).toEqual({});
    });
  });

  it('returns multiple matching cookies', () => {
    const cookies = [
      makeCookie({ name: 'a', value: '1' }),
      makeCookie({ name: 'b', value: '2' }),
      makeCookie({ name: 'c', value: '3', domain: '.other.org' }),
    ];
    const result = filterCookiesForUrl(cookies, 'https://example.com/');
    expect(result).toEqual({ a: '1', b: '2' });
  });
});

describe('resolveCookieFile', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    process.env = { ...originalEnv };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it('returns explicit path first', () => {
    process.env.AGENT_FETCH_COOKIE_FILE = '/env/path';
    expect(resolveCookieFile('/explicit/path')).toBe('/explicit/path');
  });

  it('falls back to AGENT_FETCH_COOKIE_FILE', () => {
    process.env.AGENT_FETCH_COOKIE_FILE = '/env/path';
    expect(resolveCookieFile()).toBe('/env/path');
  });

  it('returns undefined when neither set', () => {
    delete process.env.AGENT_FETCH_COOKIE_FILE;
    expect(resolveCookieFile()).toBeUndefined();
  });

  it('returns undefined for empty string explicit', () => {
    delete process.env.AGENT_FETCH_COOKIE_FILE;
    expect(resolveCookieFile('')).toBeUndefined();
  });

  it('explicit empty string overrides env var', () => {
    process.env.AGENT_FETCH_COOKIE_FILE = '/env/path';
    expect(resolveCookieFile('')).toBeUndefined();
  });
});

describe('loadCookiesFromFile', () => {
  it('returns undefined when no path specified', () => {
    expect(loadCookiesFromFile(undefined, 'https://example.com')).toBeUndefined();
  });

  it('loads and filters cookies from file', () => {
    const mockContent = `.example.com\tTRUE\t/\tFALSE\t0\tsid\tabc
.other.org\tTRUE\t/\tFALSE\t0\toid\txyz`;

    vi.mocked(readFileSync).mockReturnValueOnce(mockContent);

    const result = loadCookiesFromFile('/path/to/cookies.txt', 'https://example.com/page');
    expect(result).toEqual({ sid: 'abc' });
  });

  it('returns undefined when no cookies match', () => {
    const mockContent = `.other.org\tTRUE\t/\tFALSE\t0\toid\txyz`;

    vi.mocked(readFileSync).mockReturnValueOnce(mockContent);

    const result = loadCookiesFromFile('/path/to/cookies.txt', 'https://example.com/');
    expect(result).toBeUndefined();
  });

  it('throws with descriptive message when file not found', () => {
    vi.mocked(readFileSync).mockImplementationOnce(() => {
      throw new Error("ENOENT: no such file or directory, open '/missing.txt'");
    });

    expect(() => loadCookiesFromFile('/missing.txt', 'https://example.com/')).toThrow(
      'Failed to read cookie file: /missing.txt'
    );
  });
});

describe('mergeCookies', () => {
  it('returns undefined when both sources are undefined', () => {
    expect(mergeCookies(undefined, undefined)).toBeUndefined();
  });

  it('returns file cookies when no explicit cookies', () => {
    expect(mergeCookies({ a: '1' }, undefined)).toEqual({ a: '1' });
  });

  it('returns explicit cookies when no file cookies', () => {
    expect(mergeCookies(undefined, { b: '2' })).toEqual({ b: '2' });
  });

  it('merges both sources with explicit taking precedence', () => {
    const file = { shared: 'file', fileOnly: 'f' };
    const explicit = { shared: 'explicit', explicitOnly: 'e' };
    expect(mergeCookies(file, explicit)).toEqual({
      shared: 'explicit',
      fileOnly: 'f',
      explicitOnly: 'e',
    });
  });
});
